version: '3.8'

services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: hawkd/loftyapi:latest
    expose:
      - 8000
    command: /bin/sh -c "cd app/ && python manage.py migrate --noinput && uvicorn app.asgi:application --workers 4 --host 0.0.0.0 --port 8000"
    # command: /bin/sh -c "gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload"
    # command: /bin/sh -c "cd app/ && gunicorn app.wsgi:application --bind 0.0.0.0:8000 --reload"
    restart: always
    volumes:
      - ../..:/workspaces:cached
      # - ../app:/app

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  nginx:
    build: ../nginx/
    restart: unless-stopped
    ports:
      - 8000:80
    # volumes:
    #   - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
    #   - /home/ubuntu/ssl:/ssl/
    depends_on:
      - app
       
volumes:
  postgres-data:
