version: '3.8'

services:

  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    expose:
      - 8000
    # tty: true
    # command: gunicorn app.asgi -w 4 -k uvicorn.workers.UvicornWorker
    command: /bin/sh -c "cd app/ && gunicorn app.wsgi:application --bind 0.0.0.0:8080"
    restart: always
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    depends_on:
      - db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
   
  nginx:
    build: ../nginx/
    restart: unless-stopped
    ports:
      - 8000:80
    # volumes:
    #   - /home/ubuntu/rstudio_docker/nginx.conf:/etc/nginx/nginx.conf
    #   - /home/ubuntu/ssl:/ssl/
    depends_on:
      - app
       
  # cache:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes: 
  #     - cache:/data
volumes:
  postgres-data:
  # cache:
