# Generated by Django 4.1.6 on 2023-02-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DogImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="height", upload_to="dogs/", width_field="width"
                    ),
                ),
                ("filename", models.CharField(max_length=128)),
                ("height", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("format", models.CharField(blank=True, max_length=8, null=True)),
                ("mode", models.CharField(blank=True, max_length=8, null=True)),
                ("frames", models.PositiveIntegerField(blank=True, null=True)),
                ("bits", models.PositiveIntegerField(blank=True, null=True)),
                ("layers", models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="KeyValue",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.IntegerField(default=0)),
            ],
        ),
    ]
