# Generated by Django 4.1.6 on 2023-02-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KeyValue",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.IntegerField(default=0)),
            ],
        ),
    ]
